-- Tabela Cargo
CREATE TABLE Cargo (
    CD_CARGO INT PRIMARY KEY,
    DS_CARGO VARCHAR(255)
);

-- Tabela Municipio
CREATE TABLE Municipio (
    CD_MUNICIPIO INT PRIMARY KEY,
    NM_MUNICIPIO VARCHAR(255)
);

-- Tabela Eleicao
CREATE TABLE Eleicao (
    CD_ELEICAO INT PRIMARY KEY,
    ANO_ELEICAO INT,
    DS_ELEICAO VARCHAR(255),
    CD_TIPO_ELEICAO INT,
    NM_TIPO_ELEICAO VARCHAR(255),
    DT_ELEICAO DATE,
    NR_TURNO INT,
    TP_ABRANGENCIA VARCHAR(255)
);

-- Tabela Unidade_Eleitoral
CREATE TABLE Unidade_Eleitoral (
    SG_UE VARCHAR(10) PRIMARY KEY,
    NM_UE VARCHAR(255)
);

-- Tabela Votavel
CREATE TABLE Votavel (
    SQ_CANDIDATO INT PRIMARY KEY,
    NR_VOTAVEL INT,
    CD_CARGO INT,
    SG_UE VARCHAR(10),
    NM_VOTAVEL VARCHAR(255),
    FOREIGN KEY (CD_CARGO) REFERENCES Cargo (CD_CARGO),
    FOREIGN KEY (SG_UE) REFERENCES Unidade_Eleitoral (SG_UE)
);

-- Tabela Votacao
CREATE TABLE Votacao (
    CD_ELEICAO INT,
    CD_MUNICIPIO INT,
    NR_ZONA INT,
    NR_SECAO INT,
    CD_CARGO INT,
    NR_VOTAVEL INT,
    SG_UF VARCHAR(10),
    DT_GERACAO DATE,
    HH_GERACAO TIME,
    SG_UE VARCHAR(10),
    QT_VOTOS INT,
    NR_LOCAL_VOTACAO INT,
    NM_LOCAL_VOTACAO VARCHAR(255),
    DS_LOCAL_VOTACAO_ENDERECO VARCHAR(255),
    SQ_CANDIDATO INT,
    FOREIGN KEY (CD_ELEICAO) REFERENCES Eleicao (CD_ELEICAO),
    FOREIGN KEY (CD_MUNICIPIO) REFERENCES Municipio (CD_MUNICIPIO),
    FOREIGN KEY (CD_CARGO) REFERENCES Cargo (CD_CARGO),
    FOREIGN KEY (NR_VOTAVEL) REFERENCES Votavel (NR_VOTAVEL),
    FOREIGN KEY (SG_UE) REFERENCES Unidade_Eleitoral (SG_UE)
);
